project:
  type: website

website:
  title: "Luca Modica"
  navbar:
    left: 
      - blog.qmd
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/lucamodica
      - icon: github
        href: https://github.com/lucamodica
      - icon: twitter
        href: https://twitter.com/ThinkerBigger
    
format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    mainfont: "Source Sans Pro"
    linestretch: 1.5



