project:
  type: website

website:
  title: "Luca Modica"
  navbar:
    left: 
      - blog.qmd
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/lucamodica
      - icon: github
        href: https://github.com/lucamodica
      - icon: twitter
        href: https://twitter.com/ThinkerBigger
  description: "Luca Modica personal website."
    
format:
  html:
    theme:
      light: [cosmo, custom.scss]
      dark: [darkly, custom.scss]
    css: styles.css
    code-fold: true

